name: backy
version: 0.2.1
author: GDur <gdur.mugen@gmail.com>
description: "Backy is a neural network which is using the backpropagation algorithm.\r\
  \nIt can be instanciated with any number of layer dimensions. For example: [2, 3,\
  \ 1] which produces a net with 3 layers. The input layer has two inputs and the\
  \ output layer has 1 output neuron. The hidden layer has 3 neurons."
homepage: http://pub.dartlang.org/
documentation: https://github.com/GDur/backy
